name: Test

on: push

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Install homebrew
        run: chmod +x ./install_homebrew.sh 

      - name: Execute scripts
        run: chmod +x ./deploy.sh